### ISSUE TITLE
Issues after update to 2.2.0

### ISSUE THREAD

**Issue by PeopleInside** [Nearata/flarum-ext-twofactor#13]
Hi, after update your extension now when I login I see this

![immagine](https://github.com/Nearata/flarum-ext-twofactor/assets/5006150/95c8718f-40df-477d-bd3b-5bb19beb70bc)

Completely broken screen even without the input box where insert the code.

**Comment by Nearata** [comment]
Did you cleared cache?

**Comment by PeopleInside** [comment]
Umh seems I have to add the new translations.
Thanks.
